language: python
services:
  - postgresql
python:
    - 3.5
    - 3.6
env:
  - DB=postgres
  - DATABASE_URL=postgres://postgres@elocalhost:5432/travis_ci_test
before_script:
  # create a database
  - psql -c 'create database travis_ci_test;' -U postgres
  # Don't override install because we prefer Travis' default steps, but we
  # don't want to add this to everyone's environment.
  - pip install codecov

script:
  - pytest --cov

after_success:
  - codecov

sudo: false

